config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, expect: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, expect: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true,
                   uniqueness: { case_sensitive: false },
                   length: { minimum: 3, maximum: 25 }
end

app/models/user.rb
# Class user
class User < ApplicationRecord
  before_save { self.email = email.downcase}
  has_many :articles, dependent: :destroy
  validates :username, presence: true,
                       uniqueness: { case_sensitive: false },
                       length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    length: { maximum: 105 },
                    format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]  
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "Login needed"
      redirect_to login_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 6)
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article was created successfully."
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully."
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to article_path, status: :see_other
  end 
  
  private 
  
  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user && current_user.admin?
      flash[:alert] = "Restricted action"
      redirect_to @article
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :require_admin, except: [:index, :show]  

  def new
    @category = Category.new
  end
  def index
    @categories = Category.paginate(page: params[:page], per_page: 6)
  end
  def show
    
  end
  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category was successfully created"
      redirect_to @category 
    else
      render 'new'
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "Only admins can perform this action"
      redirect_to categories_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    
  end

  def create
    user = User.find_by(email: params[:email].downcase)
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Login in successfull"
      redirect_to user
    else
      flash.now[:alert] = "Incorrect email or password"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logout"
    redirect_to root_path, status: :see_other
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def new
    @user = User.new
  end

  def index
    @users = User.all
  end

  def show     
    @articles = @user.articles
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "User was created successfully."
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "User was updated successfully."
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    redirect_to article_path, status: :see_other
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user
      flash[:alert] = "Restricted action"
      redirect_to @user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_articles.html.erb
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row">
      <% @articles.each do |article| %>
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"> 
              <title>Placeholder</title>
              <rect width="100%" height="100%" fill="#add45c"></rect>
              <text x="50%" y="50%" dominant-baseline="middle" text-anchor="middle" fill="#eceeef" dy=".3em"><%= article.title %></text>
            </svg>
            <div class="card-body">
              <p class="card-text"><%= article.description %></p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <%= link_to 'Show', article_path(article),  class: "btn btn-sm btn-success mx-1" %>
                  <% if logged_in? && (article.user == current_user || current_user.admin?)%>
                    <%= link_to 'Edit', edit_article_path(article), class: "btn btn-sm btn-primary mx-1" %>
                    <%= link_to 'Delete', article_path(article), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-sm btn-danger mx-1" %>
                  <% end %>
                </div>
                <small class="text-muted"> Create <%= time_ago_in_words(article.created_at) %> ago</small>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <p> <%= link_to 'Create New Article', new_article_path, class: "btn btn-sm btn-success"%> </p>
  </div>
</div>

app/views/articles/_form.html.erb
<div class="container p-5 mb-4 bg-light">
  <%= render 'shared/errors', obj: @article %>
  <%= form_with(model: @article, data: {turbo: false}) do |f| %>
    <form>
      <div class="form-group row mb-5">
        <%= f.label :title, class: "form-label" %><br/>
        <%= f.text_field :title, class: "form-control", placeholder: "Enter title"%>
      </div>
      <div class="form-group row mb-5">
        <%= f.label :description, class: "form-label" %><br/>
        <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Enter description"%>
      </div>
      <div class="form-group row mb-5">
        <%= f.label :category, class: "form-label" %><br/>
        <%= f.collection_select(:category_ids, Category.all, :id, :name, { prompt: "Select suitable categories" }, { multiple: true, size: 3, class: "custom-select" } ) %>
      </div>
      <div class="form-group row justify-content-center md-5">
        <%= f.submit class: "col-5 text-center btn btn-success"%>
      </div>      
    </form>
  <% end %> 
</div>

app/views/articles/edit.html.erb
<div if="page-content">
  <h1 class="text-center mt-4">Edit article</h1>
  <%= render 'form' %>
  <p class="text-center"> <%= link_to 'Return to articles listing', articles_path, class: "btn btn-sm btn-info"%> </p>
</div>

app/views/articles/index.html.erb
<main role="main">
  <section class="text-center">
    <div class="container py-5">
      <h1 class="jumbotron-heading">Articles Listing Page</h1>
      <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
    </div>
  </section>
  <div class="flickr_pagination">
    <%= will_paginate @articles %>
  </div>
  <%= render 'articles' %>
</main>

app/views/articles/new.html.erb
<div if="page-content">
  <h1 class="text-center mt-4">Create a new article</h1>
  <%= render 'form' %>
  <p class="text-center"> <%= link_to 'Return to articles listing', articles_path, class: "btn btn-sm btn-info"%> </p>
</div>

app/views/articles/show.html.erb
<div id="page-content">
  <h2 class="text-center mt-4"><%= @article.title %></h2>
  <div class="container">
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            by <%= @article.user.username if @article.user %>
          </div>
            <% if @article.categories.any?%>
              <div class="mt-2"> <%= render @article.categories  %> </div>
            <% end %>
          <div class="card-body">
            <div class="card-text text-left"><%= simple_format(@article.description) %></div>
            <% if logged_in? && (@article.user == current_user || current_user.admin?)%>
              <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-info" %>
              <%= link_to "Delete", article_path(@article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(@article.created_at) %> ago, 
            edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  </div>
</div> 

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge rounded-pill bg-info me-1" %>

app/views/categories/_form.html.erb
<div class="container p-5 mb-4 bg-light">
  <%= render 'shared/errors', obj: @category %>
  <%= form_with(model: @category, data: {turbo: false}) do |f| %>
    <form>
      <div class="form-group row mb-5">
        <%= f.label :name, class: "form-label" %><br/>
        <%= f.text_field :name, class: "form-control", placeholder: "Enter a category name"%>
      </div>

      <div class="form-group row justify-content-center md-5">
        <%= f.submit class: "col-5 text-center btn btn-success" %>
      </div>      
    </form>
  <% end %> 
</div>

app/views/categories/index.html.erb
<main role="main">
  <section class="text-center">
    <div class="container py-5">
      <h1 class="jumbotron-heading">Categories Listing Page</h1>
      <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
    </div>
  </section>
  <div class="flickr_pagination">
    <%= will_paginate @categories %>
  </div>
  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row">
        <% @categories.each do |category| %>
          <div class="col-md-4">
            <div class="card mb-4 shadow-sm">
              <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"> 
                <title>Placeholder</title>
                <rect width="100%" height="100%" fill="#add45c"></rect>
                <text x="50%" y="50%" dominant-baseline="middle" text-anchor="middle" fill="#eceeef" dy=".3em"><%= link_to category.name, category_path(category) %></text>
              </svg>
              <div class="card-body">
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <%= link_to 'Show', category_path(category),  class: "btn btn-sm btn-success mx-1" %>
                  </div>
                  <small class="text-muted"> Created <%= time_ago_in_words(category.created_at) %> ago</small>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  
</main>

app/views/categories/new.html.erb
<div if="page-content">
  <h1 class="text-center mt-4">Create a new category</h1>
  <%= render 'form' %>
</div>

app/views/categories/show.html.erb
<div id="page-content">
  <h1 class="text-center mt-4"><%= @category.name %></h1>
  <h3 class="text-center mt-4"> Articles </h3>
  <%# <%= render 'articles/articles' %> %>
</div>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %> 
</div> 

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <div class="container-fluid">
    <%= link_to "RailsBlogApp", root_path, class: "navbar-brand", id:"logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item">
          <%= link_to "Bloggers", users_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Articles", articles_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Categories", categories_path, class:"nav-link" %>
        </li>
        <% if logged_in? %>
          <li class="nav-item">
            <%= link_to "Logout", logout_path, class:"nav-link", data: { "turbo-method": :delete }%>
          </li>
          <li class="nav-item">
            <%= link_to current_user.username, user_path(current_user), class:"nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
             <%= link_to "Login", login_path, class:"nav-link" %>
          </li>
        <% end %>
        
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "RailsBlogApp", root_path, class: "navbar-brand", id:"logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="d-flex flex-column h-100">
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container" id="home-container">
  <div class="p-5 mb-4 text-white bg-dark text-center rounded-3 jumbotron">
      <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold">Rails Blog App</h1>
        <p class="fs-4"> Using a series of utilities, you can create this jumbotron, just like the one in previous versions of Bootstrap. Check out the examples below for how you can remix and restyle it to your liking.</p>
        <%= link_to "Sign up!", signup_path, class: "btn btn-primary btn-lg btn-success"  %>
      </div>
    </div>
</div>

<footer class="footer mt-auto py-3 text-center text-white bg-dark">
  <div class="container">
    <span class="text-muted">Copyright</span>
  </div>
</footer>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="alert alert-danger alert-dismissible fade show" role="alert">
  <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase   %> from being saved</h4>
  <ul>
    <% obj.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<% end %>

app/views/users/_form.html.erb
<div class="container p-5 mb-4 bg-light">
  <%= render 'shared/errors', obj: @user %>
  <%= form_with(model: @user, data: {turbo: false}) do |f| %>
    <form>
      <div class="form-group row mb-5">
        <%= f.label :username, class: "form-label" %><br/>
        <%= f.text_field :username, class: "form-control", placeholder: "Enter username"%>
      </div>
      <div class="form-group row mb-5">
        <%= f.label :email, class: "form-label" %><br/>
        <%= f.email_field :email, class: "form-control", placeholder: "Enter email"%>
      </div>
      <div class="form-group row mb-5">
        <%= f.label :password, class: "form-label" %><br/>
        <%= f.password_field :password, class: "form-control", placeholder: "Choose a password"%>
      </div>

      <div class="form-group row justify-content-center md-5">
        <%= f.submit(@user.new_record? ? "Sign up" : "Update profile" , class: "col-5 text-center btn btn-success") %>
      </div>      
    </form>
  <% end %> 
</div>

app/views/users/edit.html.erb
<div if="page-content">
  <h1 class="text-center mt-4">Edit your profile</h1>
  <%= render 'form' %>
  <p class="text-center"> <%= link_to 'Return to user listing', user_path, class: "btn btn-sm btn-info"%> </p>
</div>

app/views/users/index.html.erb
<main role="main">
  <section class="text-center">
    <div class="container py-5">
      <h1 class="jumbotron-heading">Users Listing Page</h1>
      <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row">
        <% @users.each do |user| %>
          <div class="col-md-4">
            <div class="card mb-4 shadow-sm">
              <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"> 
                <title>Placeholder</title>
                <rect width="100%" height="100%" fill="#add45c"></rect>
                <text x="50%" y="50%" dominant-baseline="middle" text-anchor="middle" fill="#eceeef" dy=".3em"><%= user.username %></text>
              </svg>
              <div class="card-body">
                <p class="card-text"><%= user.email %></p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <%= link_to 'Show', user_path(user),  class: "btn btn-sm btn-success mx-1" %>
                    <% if logged_in? && user == current_user %>
                      <%= link_to 'Edit', edit_user_path(user), class: "btn btn-sm btn-primary mx-1" %>
                      <%= link_to 'Delete', user_path(user), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-sm btn-danger mx-1" %>
                    <% end %>
                  </div>
                  <small class="text-muted"> Create <%= time_ago_in_words(user.created_at) %> ago</small>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  
</main>

app/views/users/new.html.erb
<div if="page-content">
  <h1 class="text-center mt-4">Sign up for alpha blog</h1>
  <%= render 'form' %>
</div>

app/views/users/show.html.erb
<div id="page-content">
  <h1 class="text-center mt-4"><%= @user.username %></h1>
  <h2 class="text-center mt-4"><%= @user.email %></h2>
  <h3 class="text-center mt-4"> Articles </h3>
  <%= render 'articles/articles' %>
</div> 